---
- name: Filebeat install and launch
  hosts: webservers
  become: true
  tasks:
    - name: download filebeat 7.4.0
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: install filebeat
      command: dpkg -i filebeat-7.4.0-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: ../configs/filebeat-cfg.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable filebeat system module
      command: filebeat modules enable system

    - name: set up filebeat
      command: filebeat setup

    - name: enable filebeat service
      ansible.builtin.service:
        name: filebeat
        state: started
        enabled: yes

- name: Metricbeat install and launch
  hosts: webservers
  become: true
  tasks:
    - name: download metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: install metricbeat
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: drop in metricbeat-cfg.yml
      copy:
        src: ../configs/metricbeat-cfg.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable metricbeat docker module
      command: metricbeat modules enable docker

    - name: set up metricbeat
      command: metricbeat setup -e

    - name: enable metricbeat 
      ansible.builtin.service:
        name: metricbeat
        state: started
        enabled: yes

- name: Packetbeat install and launch
  hosts: webservers
  become: true
  tasks:
    - name: install libpcap
      apt:
        name: libpcap0.8
        state: present
        
    - name: download packetbeat 7.13.1
      get_url: 
        url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.13.1-amd64.deb
        dest: /home/azadmin/
        
    - name: install packetbeat
      command: dpkg -i packetbeat-7.13.1-amd64.deb

    - name: drop in packetbeat.yml
      copy:
        src: ../configs/packetbeat-cfg.yml
        dest: /etc/packetbeat/packetbeat.yml

    - name: set up packetbeat
      command: packetbeat setup -e

    - name: start packetbeat service
      ansible.builtin.service:
        name: packetbeat
        state: started
        enabled: yes
