---
- name: Filebeat install and launch
  hosts: webservers
  become: true
  tasks:
    - name: download filebeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: install filebeat
      command: dpkg -i filebeat-7.4.0-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: ../configs/filebeat-cfg.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable filebeat system module
      command: filebeat modules enable system

    - name: set up filebeat
      command: filebeat setup

    - name: enable filebeat service
      ansible.builtin.service:
        name: filebeat
        state: started
        enabled: yes