---
- name: Metricbeat install and launch
  hosts: webservers
  become: true
  tasks:
    - name: download metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.13.1-amd64.deb

    - name: install metricbeat
      command: dpkg -i metricbeat-7.13.1-amd64.deb

    - name: drop in metricbeat-cfg.yml
      copy:
        src: ../configs/metricbeat-cfg.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable metricbeat docker module
      command: metricbeat modules enable docker

    - name: set up metricbeat
      command: metricbeat setup -e

    - name: enable metricbeat 
      ansible.builtin.service:
        name: metricbeat
        state: started
        enabled: yes